name: Deploy to AWS

on:
  pull_request:
    branches:
      - production
      - staging_agora
  
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: Pass
        run: |
          echo "✅ PHPCS PASSED. No coding style issues found." 
          
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Fail
        run: |
          (echo "::error::❌ phpstan FAILED. --standard=PSR12 && exit 1)
          
